# Generated by Django 6.0.4 on 2026-04-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.TextField(default='abc@gmail.com', max_length=80),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.TextField(default=12345, max_length=30),
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.TextField(default='default user', max_length=50),
        ),
    ]
